version: 1
steps:
- image: gcr.io/cloud-builders/go
  dir: /root/go/src/github.com/subiz/partitioner/hello_test
  volumes:
  - $(pwd):/root/go/src/github.com/subiz/partitioner/hello_test
  command: |
    GOCACHE=/root/go/src/github.com/subiz/partitioner/hello_test/.cache CGO_ENABLED=0 go build -ldflags="-s -w" -o hello_test || exit 1
    tar -czf hello_test.tar.gz hello_test
