apiVersion: v1
kind: Service
metadata:
  name: hellotest
  labels:
    app: hellotest
spec:
  ports:
  - port: 50051
    targetPort: 50051
  clusterIP: None
  selector:
    app: hellotest
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: hellotest
  labels:
    app: hellotest
spec:
  selector:
    matchLabels:
      app: hellotest # has to match .spec.template.metadata.labels
  serviceName: hellotest
  replicas: 4
  template:
    metadata:
      labels:
        app: hellotest # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: hellotest
        image: $IMG
