// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partitioner.proto

package header

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Configuration struct {
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Term                 int32                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Cluster              string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	TotalPartitions      int32                  `protobuf:"varint,5,opt,name=total_partitions,json=totalPartitions,proto3" json:"total_partitions,omitempty"`
	NextTerm             int32                  `protobuf:"varint,6,opt,name=next_term,json=nextTerm,proto3" json:"next_term,omitempty"`
	Workers              map[string]*WorkerInfo `protobuf:"bytes,7,rep,name=workers,proto3" json:"workers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_partitioner_eb04a0a579c67470, []int{0}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Configuration) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Configuration) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Configuration) GetTotalPartitions() int32 {
	if m != nil {
		return m.TotalPartitions
	}
	return 0
}

func (m *Configuration) GetNextTerm() int32 {
	if m != nil {
		return m.NextTerm
	}
	return 0
}

func (m *Configuration) GetWorkers() map[string]*WorkerInfo {
	if m != nil {
		return m.Workers
	}
	return nil
}

type WorkerInfo struct {
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Partitions           []int32  `protobuf:"varint,7,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	Host                 string   `protobuf:"bytes,8,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerInfo) Reset()         { *m = WorkerInfo{} }
func (m *WorkerInfo) String() string { return proto.CompactTextString(m) }
func (*WorkerInfo) ProtoMessage()    {}
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_partitioner_eb04a0a579c67470, []int{1}
}
func (m *WorkerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerInfo.Unmarshal(m, b)
}
func (m *WorkerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerInfo.Marshal(b, m, deterministic)
}
func (dst *WorkerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInfo.Merge(dst, src)
}
func (m *WorkerInfo) XXX_Size() int {
	return xxx_messageInfo_WorkerInfo.Size(m)
}
func (m *WorkerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInfo proto.InternalMessageInfo

func (m *WorkerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkerInfo) GetPartitions() []int32 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

func (m *WorkerInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type GetConfigRequest struct {
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Term                 int32    `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Cluster              string   `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_partitioner_eb04a0a579c67470, []int{2}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetConfigRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *GetConfigRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type WorkerRequest struct {
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Term                 int32    `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Cluster              string   `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Id                   string   `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRequest) Reset()         { *m = WorkerRequest{} }
func (m *WorkerRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerRequest) ProtoMessage()    {}
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_partitioner_eb04a0a579c67470, []int{3}
}
func (m *WorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRequest.Unmarshal(m, b)
}
func (m *WorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRequest.Marshal(b, m, deterministic)
}
func (dst *WorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRequest.Merge(dst, src)
}
func (m *WorkerRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerRequest.Size(m)
}
func (m *WorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRequest proto.InternalMessageInfo

func (m *WorkerRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *WorkerRequest) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *WorkerRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *WorkerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WorkerRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_partitioner_eb04a0a579c67470, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Configuration)(nil), "header.Configuration")
	proto.RegisterMapType((map[string]*WorkerInfo)(nil), "header.Configuration.WorkersEntry")
	proto.RegisterType((*WorkerInfo)(nil), "header.WorkerInfo")
	proto.RegisterType((*GetConfigRequest)(nil), "header.GetConfigRequest")
	proto.RegisterType((*WorkerRequest)(nil), "header.WorkerRequest")
	proto.RegisterType((*Empty)(nil), "header.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Configuration, error)
	Leave(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error)
	Join(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error)
	Rebalance(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (Coordinator_RebalanceClient, error)
	Accept(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := c.cc.Invoke(ctx, "/header.Coordinator/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Leave(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/header.Coordinator/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Join(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/header.Coordinator/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Rebalance(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (Coordinator_RebalanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Coordinator_serviceDesc.Streams[0], "/header.Coordinator/Rebalance", opts...)
	if err != nil {
		return nil, err
	}
	x := &coordinatorRebalanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Coordinator_RebalanceClient interface {
	Recv() (*Configuration, error)
	grpc.ClientStream
}

type coordinatorRebalanceClient struct {
	grpc.ClientStream
}

func (x *coordinatorRebalanceClient) Recv() (*Configuration, error) {
	m := new(Configuration)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coordinatorClient) Accept(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/header.Coordinator/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*Configuration, error)
	Leave(context.Context, *WorkerRequest) (*Empty, error)
	Join(context.Context, *WorkerRequest) (*Empty, error)
	Rebalance(*WorkerRequest, Coordinator_RebalanceServer) error
	Accept(context.Context, *WorkerRequest) (*Empty, error)
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Coordinator/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Coordinator/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Leave(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Coordinator/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Join(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Rebalance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServer).Rebalance(m, &coordinatorRebalanceServer{stream})
}

type Coordinator_RebalanceServer interface {
	Send(*Configuration) error
	grpc.ServerStream
}

type coordinatorRebalanceServer struct {
	grpc.ServerStream
}

func (x *coordinatorRebalanceServer) Send(m *Configuration) error {
	return x.ServerStream.SendMsg(m)
}

func _Coordinator_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Coordinator/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Accept(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "header.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _Coordinator_GetConfig_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Coordinator_Leave_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Coordinator_Join_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _Coordinator_Accept_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Rebalance",
			Handler:       _Coordinator_Rebalance_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "partitioner.proto",
}

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Configuration, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Configuration, error) {
	out := new(Configuration)
	err := c.cc.Invoke(ctx, "/header.Worker/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*Configuration, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Worker/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "header.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _Worker_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partitioner.proto",
}

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Hello(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*WorkerInfo, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Hello(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*WorkerInfo, error) {
	out := new(WorkerInfo)
	err := c.cc.Invoke(ctx, "/header.Hello/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Hello(context.Context, *GetConfigRequest) (*WorkerInfo, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/header.Hello/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Hello(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "header.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Hello_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "partitioner.proto",
}

func init() { proto.RegisterFile("partitioner.proto", fileDescriptor_partitioner_eb04a0a579c67470) }

var fileDescriptor_partitioner_eb04a0a579c67470 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0xed, 0x66, 0x37, 0xd9, 0xe6, 0xae, 0xab, 0xeb, 0x85, 0xc2, 0x50, 0x41, 0x4a, 0x9e, 0xd6,
	0x97, 0x58, 0xe2, 0x83, 0x22, 0x2a, 0x4a, 0x29, 0x56, 0x11, 0x29, 0x83, 0x20, 0xf8, 0x52, 0xa6,
	0xbb, 0xb7, 0x36, 0x34, 0x9d, 0x89, 0x93, 0xc9, 0xea, 0xe2, 0xc7, 0xf8, 0x05, 0xfe, 0xa3, 0xc9,
	0x8c, 0xb3, 0xa6, 0xda, 0x85, 0x82, 0xfb, 0x76, 0xe6, 0xce, 0x39, 0xf7, 0x9e, 0x73, 0x27, 0x04,
	0xee, 0x96, 0x42, 0x9b, 0xdc, 0xe4, 0x4a, 0x92, 0x4e, 0x4b, 0xad, 0x8c, 0xc2, 0xe8, 0x9c, 0xc4,
	0x9c, 0x74, 0xf2, 0x33, 0x80, 0xf1, 0x81, 0x92, 0x67, 0xf9, 0xe7, 0x5a, 0x8b, 0x96, 0x81, 0x0c,
	0x86, 0x0b, 0xd2, 0x55, 0x03, 0x59, 0xb0, 0xd7, 0x9b, 0xc6, 0xdc, 0x1f, 0x11, 0x61, 0x60, 0x48,
	0x5f, 0xb2, 0x7e, 0x53, 0x0e, 0xb9, 0xc5, 0x2d, 0x7b, 0x56, 0xd4, 0x55, 0x83, 0xd9, 0xc0, 0xb1,
	0x7f, 0x1f, 0xf1, 0x01, 0x4c, 0x8c, 0x32, 0xa2, 0x38, 0x59, 0x0d, 0xaf, 0x58, 0x68, 0x95, 0x77,
	0x6c, 0xfd, 0x78, 0x55, 0xc6, 0x7b, 0x10, 0x4b, 0xfa, 0x66, 0x4e, 0x6c, 0xf7, 0xc8, 0x72, 0xb6,
	0xdb, 0xc2, 0x87, 0x76, 0xc2, 0x33, 0x18, 0x7e, 0x55, 0xfa, 0xa2, 0xf1, 0xc0, 0x86, 0x7b, 0xfd,
	0xe9, 0x28, 0x4b, 0x52, 0xe7, 0x3d, 0xbd, 0xe2, 0x3b, 0xfd, 0xe8, 0x48, 0x87, 0xd2, 0xe8, 0x25,
	0xf7, 0x92, 0xdd, 0xf7, 0x70, 0xab, 0x7b, 0x81, 0x13, 0xe8, 0x5f, 0xd0, 0x92, 0xf5, 0xac, 0xd7,
	0x16, 0xe2, 0x14, 0xc2, 0x85, 0x28, 0x6a, 0xb2, 0x69, 0x47, 0x19, 0xfa, 0xee, 0x4e, 0xf6, 0x46,
	0x9e, 0x29, 0xee, 0x08, 0x4f, 0x83, 0x27, 0xbd, 0xe4, 0x18, 0xe0, 0xcf, 0x05, 0xde, 0x86, 0x20,
	0x9f, 0xdb, 0x54, 0x31, 0x6f, 0x10, 0xde, 0x07, 0xe8, 0xa4, 0x6d, 0xed, 0x86, 0xbc, 0x53, 0x69,
	0x37, 0x78, 0xae, 0x2a, 0xc3, 0xb6, 0xad, 0xc2, 0xe2, 0xe4, 0x13, 0x4c, 0x5e, 0x93, 0x71, 0x59,
	0x38, 0x7d, 0xa9, 0xa9, 0x32, 0x9b, 0x7a, 0x83, 0xe4, 0x3b, 0x8c, 0x9d, 0xdb, 0x0d, 0x37, 0xfe,
	0x27, 0xb8, 0x0f, 0x16, 0x75, 0x82, 0x0d, 0x21, 0x3c, 0xbc, 0x2c, 0xcd, 0x32, 0xfb, 0x11, 0xc0,
	0xe8, 0x40, 0x29, 0x3d, 0xcf, 0xa5, 0x30, 0x4a, 0xe3, 0x0b, 0x88, 0x57, 0x89, 0x91, 0xf9, 0x7d,
	0xff, 0xbd, 0x84, 0xdd, 0x9d, 0x6b, 0xdf, 0x39, 0xd9, 0xc2, 0x87, 0x10, 0xbe, 0x23, 0xb1, 0x20,
	0xdc, 0xb9, 0xfa, 0x56, 0x5e, 0x38, 0xf6, 0x65, 0x3b, 0xbe, 0x11, 0xa4, 0x30, 0x78, 0xab, 0x72,
	0x79, 0x63, 0xfe, 0x73, 0x88, 0x39, 0x9d, 0x8a, 0x42, 0xc8, 0xd9, 0xda, 0x21, 0xeb, 0xdc, 0xed,
	0xf7, 0x70, 0x1f, 0xa2, 0x57, 0xb3, 0x19, 0x95, 0xe6, 0xa6, 0x03, 0xb3, 0x23, 0x88, 0x1c, 0xe3,
	0x7f, 0x77, 0x93, 0xbd, 0x84, 0xf0, 0x88, 0x8a, 0x42, 0xe1, 0x63, 0x0f, 0xd6, 0x37, 0xb9, 0xe6,
	0x53, 0x4f, 0xb6, 0x4e, 0x23, 0xfb, 0x83, 0x78, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x28,
	0xf3, 0xe6, 0x35, 0x04, 0x00, 0x00,
}
